### ISSUE TITLE
Could not install package from nuGet

### ISSUE THREAD

**Issue by ModernHooman** [rflechner/ScrapySharp#4]
Here is the error I get when try to install the package from nuGet or MyGet :

```
Install-Package : Could not install package 'ScrapySharp 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package ScrapySharp -Version 3.0.0 -Source https://www.myget. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 ```

**Comment by kleky** [comment]
Hi, I tried to add to a .net core console app and got the following error:

`Package restore failed. Rolling back package changes for 'scrape'.`

**Comment by clintonkopotic** [comment]
I believe it's because the project you are trying to install ScrapySharp into is targeting .NET Framework 2.0, whereas [ScrapySharp is dependent](https://www.nuget.org/packages/ScrapySharp/) on [.NET Standard 2.0](https://github.com/dotnet/standard) and according to [the .NET Standard versions table](https://github.com/dotnet/standard/blob/master/docs/versions.md) you should change your project's target to .NET Framework 4.6.1 or greater.

**Comment by doppiogrouprepos** [comment]
This still does not work, I get this same message.
Install-Package : Could not install package 'ScrapySharp 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package ScrapySharp -Version 3.0.0 -Source https://www.myget. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
